version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - depguard
    - exhaustruct
    - gochecknoglobals
    - godot
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - mnd
    - nlreturn
    - varnamelen
    - wsl
    - zerologlint
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    godox:
      keywords:
        - FIXME
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - importas
    mnd:
      ignored-functions:
        - ^v\.SetDefault
    nestif:
      min-complexity: 10
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    paralleltest:
      ignore-missing: true
      ignore-missing-subtests: true
    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
