name: build

on:
  workflow_run:
    workflows: ["lint"]
    types:
      - completed
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build binary
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            golang:1.23-alpine3.20 \
            go build -v -ldflags="-s -w" -o nvidiactl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nvidiactl
          path: nvidiactl
