name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, docker]
    container:
      image: code.forgejo.org/oci/golang:1.23-alpine3.20
      options: --user root
    steps:
      - uses: https://github.com/actions/checkout@v3

      - name: Build
        run: go build -v -ldflags="-s -w" -o nvidiactl

      - name: Upload artifact
        uses: https://github.com/actions/upload-artifact@v4
        with:
          name: nvidiactl
          path: nvidiactl
