name: build

on:
  push:
    branches:
      - main

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  lint:
    uses: ./.forgejo/workflows/lint.yaml

  build:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Print Go module info
        run: |
          go list -m all
          cat go.mod

      - name: Build binary
        run: |
          go version
          go env
          go mod download
          go build -v -o nvidiactl ./cmd/nvidiactl

      - name: List built artifacts
        run: |
          file nvidiactl || echo "nvidiactl not found"
