name: release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.FORGEJO_TOKEN }}
          default_bump: patch
          release_branches: main
          create_annotated_tag: true
          tag_prefix: v

      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: nvidiactl
          run_id: ${{ github.event.workflow_run.id }}

      - name: release
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e FORGEJO_TOKEN \
            alpine:3.20 \
            /bin/sh -c "
              apk add --no-cache curl
              curl -s https://raw.githubusercontent.com/forgejoactions/forgejo-api/main/install.sh | sh
              /root/bin/forgejo release create \
                --tag-name ${{ steps.tag_version.outputs.new_version }} \
                --title 'Release ${{ steps.tag_version.outputs.new_version }}' \
                --draft=false \
                --prerelease=false \
                --repo ${{ github.repository }} \
                --attach ./nvidiactl
            "
